// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swallow.Data;

#nullable disable

namespace Swallow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttractionsToCategories", b =>
                {
                    b.Property<int>("AttractionCategoriesAttractionCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AttractionsAttractionId")
                        .HasColumnType("int");

                    b.HasKey("AttractionCategoriesAttractionCategoryId", "AttractionsAttractionId");

                    b.HasIndex("AttractionsAttractionId");

                    b.ToTable("AttractionsToCategories");
                });

            modelBuilder.Entity("Swallow.Models.Attraction", b =>
                {
                    b.Property<int>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttractionId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<short?>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Popularity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("TripAdvisorUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserRatingsTotal")
                        .HasColumnType("int");

                    b.Property<string>("VisitDuration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AttractionId");

                    b.HasIndex("CityId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("Swallow.Models.AttractionCategory", b =>
                {
                    b.Property<int>("AttractionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttractionCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("AttractionCategoryId");

                    b.ToTable("AttractionCategories");
                });

            modelBuilder.Entity("Swallow.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TripAdvisorUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Swallow.Models.Country", b =>
                {
                    b.Property<short>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CountryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CountryId");

                    b.HasIndex("Iso2")
                        .IsUnique();

                    b.HasIndex("Iso3")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Swallow.Models.Currency", b =>
                {
                    b.Property<short>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CurrencyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<short?>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("CurrencyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Swallow.Models.CurrencyRate", b =>
                {
                    b.Property<int>("CurrencyRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyRateId"));

                    b.Property<short>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RateToUSD")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("CurrencyRateId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("Swallow.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Swallow.Models.Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short?>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("ExpenseCategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("TripId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Swallow.Models.ExpenseCategory", b =>
                {
                    b.Property<short>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ExpenseCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ExpenseCategoryId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("Swallow.Models.ItineraryAttraction", b =>
                {
                    b.Property<int>("ItineraryAttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryAttractionId"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.Property<short?>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryDayId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TicketsURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ItineraryAttractionId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ItineraryDayId");

                    b.ToTable("ItineraryAttractions");
                });

            modelBuilder.Entity("Swallow.Models.ItineraryDay", b =>
                {
                    b.Property<int>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryDayId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("TripId");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("Swallow.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<bool>("Ads")
                        .HasColumnType("bit");

                    b.Property<bool>("ChatbotAccess")
                        .HasColumnType("bit");

                    b.Property<int>("MaxAttractions")
                        .HasColumnType("int");

                    b.Property<int>("MaxTripDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxTrips")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PersonalizeItinerary")
                        .HasColumnType("bit");

                    b.Property<bool>("PhoneAccess")
                        .HasColumnType("bit");

                    b.Property<string>("PriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TripTips")
                        .HasColumnType("bit");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Ads = true,
                            ChatbotAccess = false,
                            MaxAttractions = 10,
                            MaxTripDays = 3,
                            MaxTrips = 3,
                            Name = "Free",
                            PersonalizeItinerary = false,
                            PhoneAccess = false,
                            TripTips = false
                        },
                        new
                        {
                            PlanId = 2,
                            Ads = false,
                            ChatbotAccess = true,
                            MaxAttractions = 50,
                            MaxTripDays = 10,
                            MaxTrips = 10,
                            Name = "Premium",
                            PersonalizeItinerary = true,
                            PhoneAccess = true,
                            TripTips = true
                        },
                        new
                        {
                            PlanId = 3,
                            Ads = false,
                            ChatbotAccess = true,
                            MaxAttractions = 50,
                            MaxTripDays = 10,
                            MaxTrips = 100,
                            Name = "Business",
                            PersonalizeItinerary = true,
                            PhoneAccess = false,
                            TripTips = false
                        });
                });

            modelBuilder.Entity("Swallow.Models.PlatformSettings", b =>
                {
                    b.Property<byte>("SettingsId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("LastCurrencyUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextCurrencyUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingsId");

                    b.ToTable("PlatformSettings");

                    b.HasData(
                        new
                        {
                            SettingsId = (byte)1,
                            MaintenanceMode = false,
                            NextCurrencyUpdate = new DateTime(2024, 4, 12, 9, 39, 38, 807, DateTimeKind.Utc).AddTicks(8624)
                        });
                });

            modelBuilder.Entity("Swallow.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e90091a7-40ba-46c5-beb5-0a608c972756"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("eb634a23-4388-47d5-8b21-07a509e8a42d"),
                            Name = "Premium",
                            NormalizedName = "PREMIUM"
                        });
                });

            modelBuilder.Entity("Swallow.Models.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Swallow.Models.Schedule", b =>
                {
                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.Property<byte>("WeekdayId")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("AttractionId", "WeekdayId");

                    b.HasIndex("WeekdayId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Swallow.Models.TransportMode", b =>
                {
                    b.Property<byte>("TransportModeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TransportModeId");

                    b.ToTable("TransportModes");
                });

            modelBuilder.Entity("Swallow.Models.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TripId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Swallow.Models.TripTransport", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("TransportModeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<short?>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TicketsURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TransportNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TripId", "TransportModeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TransportModeId");

                    b.ToTable("TripTransports");
                });

            modelBuilder.Entity("Swallow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("HasCustomProfilePicture")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProfilePicturePath")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<string>("PublicUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PublicUsername")
                        .IsUnique()
                        .HasFilter("[PublicUsername] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Swallow.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("Swallow.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Swallow.Models.UserPlan", b =>
                {
                    b.Property<int>("UserPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPlanId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTrips")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserPlanId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlans");
                });

            modelBuilder.Entity("Swallow.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Swallow.Models.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Swallow.Models.Weekday", b =>
                {
                    b.Property<byte>("WeekdayId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("WeekdayId");

                    b.ToTable("Weekdays");

                    b.HasData(
                        new
                        {
                            WeekdayId = (byte)1,
                            Name = "Monday"
                        },
                        new
                        {
                            WeekdayId = (byte)2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            WeekdayId = (byte)3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            WeekdayId = (byte)4,
                            Name = "Thursday"
                        },
                        new
                        {
                            WeekdayId = (byte)5,
                            Name = "Friday"
                        },
                        new
                        {
                            WeekdayId = (byte)6,
                            Name = "Saturday"
                        },
                        new
                        {
                            WeekdayId = (byte)7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("AttractionsToCategories", b =>
                {
                    b.HasOne("Swallow.Models.AttractionCategory", null)
                        .WithMany()
                        .HasForeignKey("AttractionCategoriesAttractionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.Attraction", null)
                        .WithMany()
                        .HasForeignKey("AttractionsAttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Swallow.Models.Attraction", b =>
                {
                    b.HasOne("Swallow.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.Currency", "Currency")
                        .WithMany("Attractions")
                        .HasForeignKey("CurrencyId");

                    b.Navigation("City");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Swallow.Models.City", b =>
                {
                    b.HasOne("Swallow.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Swallow.Models.Currency", b =>
                {
                    b.HasOne("Swallow.Models.Country", "Country")
                        .WithMany("Currencies")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Swallow.Models.CurrencyRate", b =>
                {
                    b.HasOne("Swallow.Models.Currency", "Currency")
                        .WithMany("CurrencyRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Swallow.Models.Expense", b =>
                {
                    b.HasOne("Swallow.Models.Currency", "Currency")
                        .WithMany("Expenses")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Swallow.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.Trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Swallow.Models.ItineraryAttraction", b =>
                {
                    b.HasOne("Swallow.Models.Attraction", "Attraction")
                        .WithMany("ItineraryAttractions")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.Currency", "Currency")
                        .WithMany("ItineraryAttractions")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Swallow.Models.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryAttractions")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Currency");

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("Swallow.Models.ItineraryDay", b =>
                {
                    b.HasOne("Swallow.Models.Trip", "Trip")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Swallow.Models.RoleClaim", b =>
                {
                    b.HasOne("Swallow.Models.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Swallow.Models.Schedule", b =>
                {
                    b.HasOne("Swallow.Models.Attraction", "Attraction")
                        .WithMany("Schedules")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.Weekday", "Weekday")
                        .WithMany("Schedules")
                        .HasForeignKey("WeekdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Weekday");
                });

            modelBuilder.Entity("Swallow.Models.Trip", b =>
                {
                    b.HasOne("Swallow.Models.City", "City")
                        .WithMany("Trips")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swallow.Models.TripTransport", b =>
                {
                    b.HasOne("Swallow.Models.Currency", "Currency")
                        .WithMany("TripTransports")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Swallow.Models.TransportMode", "TransportMode")
                        .WithMany("TripTransports")
                        .HasForeignKey("TransportModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.Trip", "Trip")
                        .WithMany("TripTransports")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("TransportMode");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Swallow.Models.UserClaim", b =>
                {
                    b.HasOne("Swallow.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swallow.Models.UserLogin", b =>
                {
                    b.HasOne("Swallow.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swallow.Models.UserPlan", b =>
                {
                    b.HasOne("Swallow.Models.Plan", "Plan")
                        .WithMany("UserPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.User", "User")
                        .WithMany("UserPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swallow.Models.UserRole", b =>
                {
                    b.HasOne("Swallow.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swallow.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swallow.Models.UserToken", b =>
                {
                    b.HasOne("Swallow.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Swallow.Models.Attraction", b =>
                {
                    b.Navigation("ItineraryAttractions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Swallow.Models.City", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Swallow.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Currencies");
                });

            modelBuilder.Entity("Swallow.Models.Currency", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("CurrencyRates");

                    b.Navigation("Expenses");

                    b.Navigation("ItineraryAttractions");

                    b.Navigation("TripTransports");
                });

            modelBuilder.Entity("Swallow.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Swallow.Models.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryAttractions");
                });

            modelBuilder.Entity("Swallow.Models.Plan", b =>
                {
                    b.Navigation("UserPlans");
                });

            modelBuilder.Entity("Swallow.Models.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Swallow.Models.TransportMode", b =>
                {
                    b.Navigation("TripTransports");
                });

            modelBuilder.Entity("Swallow.Models.Trip", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("ItineraryDays");

                    b.Navigation("TripTransports");
                });

            modelBuilder.Entity("Swallow.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("Trips");

                    b.Navigation("UserPlans");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Swallow.Models.Weekday", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
